// <auto-generated />
using System;
using ElectricityCompany.EF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectricityCompany.EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240721232800_Create")]
    partial class Create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElectricityCompany.Core.Model.FTA.Channel", b =>
                {
                    b.Property<int>("Channel_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Channel_Key"));

                    b.Property<string>("Channel_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Channel_Key");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.FTA.Cutting_Down_Detail", b =>
                {
                    b.Property<int>("Cutting_Down_Detail_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cutting_Down_Detail_Key"));

                    b.Property<DateOnly>("ActualCreatetDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ActualEndDate")
                        .HasColumnType("date");

                    b.Property<int>("Cutting_Down_Key")
                        .HasColumnType("int");

                    b.Property<int>("ImpactedCustomers")
                        .HasColumnType("int");

                    b.Property<int>("Network_Element_Key")
                        .HasColumnType("int");

                    b.HasKey("Cutting_Down_Detail_Key");

                    b.HasIndex("Cutting_Down_Key");

                    b.HasIndex("Network_Element_Key");

                    b.ToTable("Cutting_Down_Details");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.FTA.Cutting_Down_Header", b =>
                {
                    b.Property<int>("Cutting_Down_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cutting_Down_Key"));

                    b.Property<DateOnly>("ActualCreatetDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ActualEndDate")
                        .HasColumnType("date");

                    b.Property<int>("Channel_Key")
                        .HasColumnType("int");

                    b.Property<string>("CreateSystemUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cutting_Down_Incident_ID")
                        .HasColumnType("int");

                    b.Property<int>("Cutting_Down_Problem_Type_Key")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPlanned")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("PlannedEndDTS")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PlannedStartDTS")
                        .HasColumnType("date");

                    b.Property<DateOnly>("SynchCreateDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("SynchUpdateDate")
                        .HasColumnType("date");

                    b.Property<string>("UpdateSystemUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cutting_Down_Key");

                    b.HasIndex("Channel_Key");

                    b.HasIndex("Cutting_Down_Incident_ID");

                    b.HasIndex("Cutting_Down_Problem_Type_Key");

                    b.ToTable("Cutting_Down_Headers");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.FTA.Cutting_Down_Ignored", b =>
                {
                    b.Property<int>("Cutting_Down_Incident_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cutting_Down_Incident_ID"));

                    b.Property<DateOnly>("ActualCreatetDate")
                        .HasColumnType("date");

                    b.Property<string>("Cabel_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cabin_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("SynchCreateDate")
                        .HasColumnType("date");

                    b.HasKey("Cutting_Down_Incident_ID");

                    b.ToTable("Cutting_Down_Ignoreds");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.FTA.Network_Element", b =>
                {
                    b.Property<int>("Network_Element_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Network_Element_Key"));

                    b.Property<string>("Network_Element_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nework_Element_Type_key")
                        .HasColumnType("int");

                    b.HasKey("Network_Element_Key");

                    b.HasIndex("Nework_Element_Type_key");

                    b.ToTable("Network_Elements");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.FTA.Netwrok_Element_Hierarchy_Path", b =>
                {
                    b.Property<int>("Network_Element_Hierarchy_Path_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Network_Element_Hierarchy_Path_Key"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Netwrok_Element_Hierarchy_Path_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Network_Element_Hierarchy_Path_Key");

                    b.ToTable("Netwrok_Element_Hierarchy_Paths");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.FTA.Netwrok_Element_Type", b =>
                {
                    b.Property<int>("Nework_Element_Type_key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Nework_Element_Type_key"));

                    b.Property<int>("Network_Element_Hierarchy_Path_Key")
                        .HasColumnType("int");

                    b.Property<string>("Network_Element_Type_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Nework_Element_Type_key");

                    b.HasIndex("Network_Element_Hierarchy_Path_Key");

                    b.ToTable("Netwrok_Element_Types");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.JWT.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Block", b =>
                {
                    b.Property<int>("Block_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Block_Key"));

                    b.Property<string>("Block_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cable_Key")
                        .HasColumnType("int");

                    b.HasKey("Block_Key");

                    b.HasIndex("Cable_Key");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Building", b =>
                {
                    b.Property<int>("Building_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Building_Key"));

                    b.Property<int>("Block_Key")
                        .HasColumnType("int");

                    b.Property<string>("Building_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Building_Key");

                    b.HasIndex("Block_Key");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Cabin", b =>
                {
                    b.Property<int>("Cabin_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cabin_Key"));

                    b.Property<string>("Cabin_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tower_Key")
                        .HasColumnType("int");

                    b.HasKey("Cabin_Key");

                    b.HasIndex("Tower_Key");

                    b.ToTable("Cabins");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Cable", b =>
                {
                    b.Property<int>("Cable_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cable_Key"));

                    b.Property<int>("Cabin_Key")
                        .HasColumnType("int");

                    b.Property<string>("Cable_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cable_Key");

                    b.HasIndex("Cabin_Key");

                    b.ToTable("Cables");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.City", b =>
                {
                    b.Property<int>("City_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("City_Key"));

                    b.Property<string>("City_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Zone_Key")
                        .HasColumnType("int");

                    b.HasKey("City_Key");

                    b.HasIndex("Zone_Key");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Cutting_Down_A", b =>
                {
                    b.Property<int>("Cutting_Down_A_Incident_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cutting_Down_A_Incident_ID"));

                    b.Property<DateOnly>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cutting_Down_Cabin_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPlanned")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("PlannedEndDTS")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PlannedStartDTS")
                        .HasColumnType("date");

                    b.Property<int>("Problem_Type_Key")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cutting_Down_A_Incident_ID");

                    b.HasIndex("Problem_Type_Key");

                    b.ToTable("Cutting_Down_As");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Cutting_Down_B", b =>
                {
                    b.Property<int>("Cutting_Down_B_Incident_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cutting_Down_B_Incident_ID"));

                    b.Property<DateOnly>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cutting_Down_Cable_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPlanned")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("PlannedEndDTS")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PlannedStartDTS")
                        .HasColumnType("date");

                    b.Property<int>("Problem_Type_Key")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cutting_Down_B_Incident_ID");

                    b.HasIndex("Problem_Type_Key");

                    b.ToTable("Cutting_Down_Bs");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Flat", b =>
                {
                    b.Property<int>("Flat_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Flat_Key"));

                    b.Property<int>("Building_Key")
                        .HasColumnType("int");

                    b.HasKey("Flat_Key");

                    b.HasIndex("Building_Key");

                    b.ToTable("Flats");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Governrate", b =>
                {
                    b.Property<int>("Governrate_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Governrate_Key"));

                    b.Property<string>("Governrate_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Governrate_Key");

                    b.ToTable("Governrates");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Problem_Type", b =>
                {
                    b.Property<int>("Problem_Type_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Problem_Type_Key"));

                    b.Property<string>("problem_Type_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Problem_Type_Key");

                    b.ToTable("Problem_Types");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Sector", b =>
                {
                    b.Property<int>("Sector_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sector_Key"));

                    b.Property<int>("Governrate_Key")
                        .HasColumnType("int");

                    b.Property<string>("Sector_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sector_Key");

                    b.HasIndex("Governrate_Key");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Station", b =>
                {
                    b.Property<int>("Station_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Station_Key"));

                    b.Property<int>("City_Key")
                        .HasColumnType("int");

                    b.Property<string>("Station_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Station_Key");

                    b.HasIndex("City_Key");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Subscription", b =>
                {
                    b.Property<int>("Subscription_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Subscription_Key"));

                    b.Property<int>("Flat_Key")
                        .HasColumnType("int");

                    b.HasKey("Subscription_Key");

                    b.HasIndex("Flat_Key");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Tower", b =>
                {
                    b.Property<int>("Tower_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Tower_Key"));

                    b.Property<int>("Station_Key")
                        .HasColumnType("int");

                    b.Property<string>("Tower_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Tower_Key");

                    b.HasIndex("Station_Key");

                    b.ToTable("Towers");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Zone", b =>
                {
                    b.Property<int>("Zone_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Zone_Key"));

                    b.Property<int>("Sector_Key")
                        .HasColumnType("int");

                    b.Property<string>("Zone_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Zone_Key");

                    b.HasIndex("Sector_Key");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.FTA.Cutting_Down_Detail", b =>
                {
                    b.HasOne("ElectricityCompany.Core.Model.FTA.Cutting_Down_Header", "Cutting_Down_Header")
                        .WithMany("Cutting_Down_Details")
                        .HasForeignKey("Cutting_Down_Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectricityCompany.Core.Model.FTA.Network_Element", "Network_Element")
                        .WithMany("Cutting_Down_Details")
                        .HasForeignKey("Network_Element_Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cutting_Down_Header");

                    b.Navigation("Network_Element");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.FTA.Cutting_Down_Header", b =>
                {
                    b.HasOne("ElectricityCompany.Core.Model.FTA.Channel", "Channel")
                        .WithMany("Cutting_Down_Headers")
                        .HasForeignKey("Channel_Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectricityCompany.Core.Model.FTA.Cutting_Down_Ignored", "Cutting_Down_Ignored")
                        .WithMany("Cutting_Down_Headers")
                        .HasForeignKey("Cutting_Down_Incident_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectricityCompany.Core.Model.STA.Problem_Type", "Problem_Type")
                        .WithMany("Cutting_Down_Headers")
                        .HasForeignKey("Cutting_Down_Problem_Type_Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Cutting_Down_Ignored");

                    b.Navigation("Problem_Type");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.FTA.Network_Element", b =>
                {
                    b.HasOne("ElectricityCompany.Core.Model.FTA.Netwrok_Element_Type", "Netwrok_Element_Type")
                        .WithMany("Network_Elements")
                        .HasForeignKey("Nework_Element_Type_key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Netwrok_Element_Type");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.FTA.Netwrok_Element_Type", b =>
                {
                    b.HasOne("ElectricityCompany.Core.Model.FTA.Netwrok_Element_Hierarchy_Path", "Netwrok_Element_Hierarchy_Path")
                        .WithMany("Netwrok_Element_Types")
                        .HasForeignKey("Network_Element_Hierarchy_Path_Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Netwrok_Element_Hierarchy_Path");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Block", b =>
                {
                    b.HasOne("ElectricityCompany.Core.Model.STA.Cable", "Cable")
                        .WithMany("Blocks")
                        .HasForeignKey("Cable_Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cable");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Building", b =>
                {
                    b.HasOne("ElectricityCompany.Core.Model.STA.Block", "Block")
                        .WithMany("Buildings")
                        .HasForeignKey("Block_Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Cabin", b =>
                {
                    b.HasOne("ElectricityCompany.Core.Model.STA.Tower", "Tower")
                        .WithMany("Cabins")
                        .HasForeignKey("Tower_Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tower");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Cable", b =>
                {
                    b.HasOne("ElectricityCompany.Core.Model.STA.Cabin", "Cabin")
                        .WithMany("Cables")
                        .HasForeignKey("Cabin_Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabin");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.City", b =>
                {
                    b.HasOne("ElectricityCompany.Core.Model.STA.Zone", "Zone")
                        .WithMany("Cities")
                        .HasForeignKey("Zone_Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Cutting_Down_A", b =>
                {
                    b.HasOne("ElectricityCompany.Core.Model.STA.Problem_Type", "Problem_Type")
                        .WithMany("Cutting_Down_As")
                        .HasForeignKey("Problem_Type_Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem_Type");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Cutting_Down_B", b =>
                {
                    b.HasOne("ElectricityCompany.Core.Model.STA.Problem_Type", "Problem_Type")
                        .WithMany("Cutting_Down_Bs")
                        .HasForeignKey("Problem_Type_Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem_Type");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Flat", b =>
                {
                    b.HasOne("ElectricityCompany.Core.Model.STA.Building", "Building")
                        .WithMany("Flats")
                        .HasForeignKey("Building_Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Sector", b =>
                {
                    b.HasOne("ElectricityCompany.Core.Model.STA.Governrate", "Governrate")
                        .WithMany("Sectors")
                        .HasForeignKey("Governrate_Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Governrate");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Station", b =>
                {
                    b.HasOne("ElectricityCompany.Core.Model.STA.City", "City")
                        .WithMany("Stations")
                        .HasForeignKey("City_Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Subscription", b =>
                {
                    b.HasOne("ElectricityCompany.Core.Model.STA.Flat", "Flat")
                        .WithMany("Subscriptions")
                        .HasForeignKey("Flat_Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flat");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Tower", b =>
                {
                    b.HasOne("ElectricityCompany.Core.Model.STA.Station", "Station")
                        .WithMany("Towers")
                        .HasForeignKey("Station_Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Zone", b =>
                {
                    b.HasOne("ElectricityCompany.Core.Model.STA.Sector", "Sector")
                        .WithMany("Zones")
                        .HasForeignKey("Sector_Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ElectricityCompany.Core.Model.JWT.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ElectricityCompany.Core.Model.JWT.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectricityCompany.Core.Model.JWT.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ElectricityCompany.Core.Model.JWT.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.FTA.Channel", b =>
                {
                    b.Navigation("Cutting_Down_Headers");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.FTA.Cutting_Down_Header", b =>
                {
                    b.Navigation("Cutting_Down_Details");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.FTA.Cutting_Down_Ignored", b =>
                {
                    b.Navigation("Cutting_Down_Headers");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.FTA.Network_Element", b =>
                {
                    b.Navigation("Cutting_Down_Details");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.FTA.Netwrok_Element_Hierarchy_Path", b =>
                {
                    b.Navigation("Netwrok_Element_Types");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.FTA.Netwrok_Element_Type", b =>
                {
                    b.Navigation("Network_Elements");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Block", b =>
                {
                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Building", b =>
                {
                    b.Navigation("Flats");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Cabin", b =>
                {
                    b.Navigation("Cables");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Cable", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.City", b =>
                {
                    b.Navigation("Stations");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Flat", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Governrate", b =>
                {
                    b.Navigation("Sectors");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Problem_Type", b =>
                {
                    b.Navigation("Cutting_Down_As");

                    b.Navigation("Cutting_Down_Bs");

                    b.Navigation("Cutting_Down_Headers");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Sector", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Station", b =>
                {
                    b.Navigation("Towers");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Tower", b =>
                {
                    b.Navigation("Cabins");
                });

            modelBuilder.Entity("ElectricityCompany.Core.Model.STA.Zone", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
